Update README.md
OceanicJS/Oceanic pull request #22
Opened 2022-10-02 19:54 UTC by Infinixius

Update README with new title, shields.io badges, and code example.

2022-10-02 20:01 UTC, DonovanDMC requested changes

2022-10-02 20:01 UTC, DonovanDMC commented on README.md
> +const client = new Oceanic.Client({ auth: "Bot [TOKEN]" });
```suggestion
const { Client } = require("oceanic.js");
const client = new Client({ auth: "Bot [TOKEN]" });
```

2022-10-02 20:01 UTC, DonovanDMC commented on README.md
> +
```suggestion

client.on("error", (err) => {
    console.error("Something Broke!", err);
});

```

2022-10-02 20:01 UTC, DonovanDMC commented on README.md
>  <hr>
```suggestion

For more examples, see the [examples](https://github.com/OceanicJS/Oceanic/tree/dev/examples) folder on github.
<hr>
```

Github's being a pain in the ass, it won't let me have those 3 backticks up there in the suggestion

2022-10-02 20:23 UTC, ray-1337 requested changes

2022-10-02 20:23 UTC, ray-1337 commented on README.md
> +const client = new Oceanic.Client({ auth: "Bot [TOKEN]" });
maybe you can remove the Oceanic to `new Client`

2022-10-03 09:43 UTC, DonovanDMC approved these changes

2022-10-03 09:45 UTC, merged